#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/academic;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-54-180-132-139.ap-northeast-2.compute.amazonaws.com:3306/springdb?serverTimezone=Asia/Seoul
    username: spring
    password: spring

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace